version: '3.5'    
services:
  spotlight.en:
    image: dbpedia/dbpedia-spotlight
    container_name: dbpedia-spotlight.fr
    volumes:
       - spotlight-models:/opt/spotlight/models
    restart: unless-stopped   
    ports:
       - "0.0.0.0:2222:80"  
    command: /bin/spotlight.sh fr
     
volumes:
  spotlight-models:
    external: true
