version: '3.5'    
services:
  spotlight.fr:
    build:
        context: .
        dockerfile: dockerfile
    image: wimmics/dbpedia-spotlight
    container_name: dbpedia-spotlight.fr
    env_file: .env
    volumes:
       - ${FILE_DIR}:/opt/spotlight/models
    restart: unless-stopped
    ports:
       - "0.0.0.0:2223:80"  
    networks:
       - spotlight-net
    command: /bin/spotlight.sh fr
      
  web:
    image: dbpedia/dbpedia-spotlight-html-view
    container_name: spotlight-demo
    env_file: .env
    ports:
      - "0.0.0.0:2222:80"
    volumes:
      - ${FILE_DIR}/sites_just_fr.xml:/var/www/html/config/sites_just_fr.xml
    restart: unless-stopped
    networks:
        - spotlight-net

networks:
    spotlight-net:
        name: spotlight-net
        driver: bridge
