version: '3.5'    
services:
  spotlight.fr:
    image: dbpedia/dbpedia-spotlight
    container_name: dbpedia-spotlight.fr
    volumes:
       - /appli/dbpedia_proj-data/spotlight:/opt/spotlight/models
    restart: always
    ports:
       - "0.0.0.0:2223:80"  
    networks:
       - spotlight-net
    command: /bin/spotlight.sh fr
      
  web:
    image: dbpedia/dbpedia-spotlight-html-view
    container_name: spotlight-demo
    ports:
      - "0.0.0.0:2222:80"
    volumes:
      - type: bind
           source: "$(pwd)"/sites_just_fr.xml
           target: /var/www/html/config/sites.xml
    networks:
        - spotlight-net

networks:
    spotlight-net:
        name: spotlight-net
        driver: bridge




